org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=iron_magic_duel
mod_version=1.20.1-1.0.64
mod_group_id=com.example.scrollspellicons
mod_name=Iron Magic Duel
mod_license=MIT
mod_authors=MKUXQQ
mod_description=Iron Magic Duel: duel, shop, HUD and spell performance helpers for Forge 1.20.1.

irons_spellbooks_jar=E:/我的世界/.minecraft/versions/铁魔法1.20.1的/mods/[Iron的法术与魔法书] irons_spellbooks-1.20.1-3.16.1.jar
curios_jar=E:/我的世界/.minecraft/versions/铁魔法1.20.1的/mods/curios-forge-5.14.1+1.20.1.jar
