modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
logoFile = "icon.png"
description = '''${mod_description}'''

[[mixins]]
config = "iron_magic_duel.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "irons_spellbooks"
type = "required"
versionRange = "[1.21.1-3.13.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "uilib"
type = "required"
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "curios"
type = "required"
versionRange = "[9.5.1,)"
ordering = "AFTER"
side = "BOTH"
